name "Vite React Components"

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@latest
      - name: node
        uses: actions/setup-node@latest
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: publish
        run: np publish --access public
        env:
          NODE_AUTH_ACTION: ${{secrets.NPM_AUTH_TOKEN}}